version: '3'
services: 
    mariadb:
        image: bitnami/mariadb
        volumes:
            - '~/restaurante/mariadb_data:/bitnami/mariadb'
        environment: 
            - ALLOW_EMPTY_PASSWORD=yes
            - MARIADB_USER=bn_wordpress
            - MARIADB_PASSWORD=bitnami
            - MARIADB_DATABASE=bitnami_wordpress

    wordpress:
        image: bitnami/wordpress
        ports:
            - '8080:8080'
            - '8443:8443'
        volumes:
            - '~/restaurante/wordpress_data:/bitnami/wordpress'
        depends_on: 
            - mariadb
        environment: 
            - ALLOW_EMPTY_PASSWORD=yes
            - WORDPRESS_DATABASE_PASSWORD=bitnami
            - WORDPRESS_DATABASE_USER=bn_wordpress
            - WORDPRESS_DATABASE_NAME=bitnami_wordpress
